image: maven:latest

stages:
  - build
  - test
  - package
  - deploy

cache:
  paths:
    - target/

build_app:
  stage: build
  script:
    - mvn compile

test_app:
  stage: test
  script:
    - mvn test

package_app:
  stage: package
  script:
    - mvn clean package -P webapp

deploy_app:
    stage: deploy
    script:
    - echo "Deploy review app"
    artifacts:
        name: "webCalculator"
        paths:
        - target/*.jar
