stages:
  - build
  - test
  - package
  - deploy

variables:
  JAVA_HOME: /home/vagrant/java/jdk-11.0.12

before_script:
  - echo "Working"

cache:
  paths:
    - target/

build_app:
  stage: build
  script:
    - mvn compile

test_app:
  stage: test
  script:
    - mvn test

package_app:
  stage: package
  script:
    - mvn clean package -P webapp

deploy_app:
    stage: deploy
    script:
    - echo "Deploy review app"
    artifacts:
        name: "webCalculator"
        paths:
        - target/*.jar
