stages:
  - build
  - unit_test
  - package
  - artifactory
  - deploy_staging
  - release

variables:
  JAVA_HOME: /home/vagrant/java/jdk-11.0.12

before_script:
  - echo "Working"

cache:
  paths:
    - target/
    - .m2/repository




build_app:
  stage: build
  tags:
    - integration
  script:
    - mvn compile

test_app:
  stage: unit_test
  tags:
    - integration
  script:
    - mvn test

package_app:
  stage: package
  tags:
    - integration
  script:
    - mvn clean package -P webapp

deploy_app_on_artifactory:
    stage: artifactory
    tags:
      - integration
    script:
    - echo "Deploy review app"
    artifacts:
        name: "webCalculator"
        paths:
        - target/*.war

deploy_on_staging_and_test:
  stage: deploy_staging
  tags:
    - staging
  script:
    - rm -f /home/vagrant/calculator-0.0.1-SNAPSHOT*
    - cp target/*.war /home/vagrant/
    - java -jar /home/vagrant/calculator-0.0.1-SNAPSHOT-tests.war

release_app:
  stage: release
  tags:
    - releasing
  script:
    - PID=`ps -ef | grep calculator-0.0.1-SNAPSHOT.war | awk '{ print $2 }'`
    - kill -9 $PID
    - rm -f /home/vagrant/calculator-0.0.1-SNAPSHOT*
    - cp target/*.war /home/vagrant/
    - java -jar /home/vagrant/calculator-0.0.1-SNAPSHOT.war