---

- name: "Check if GitLab-runner is already installed."
  stat: "path={{HOME}}/runner_is_installed.flag"
  register: flag

- name: "Install GitLab-runner."
  shell: |
    curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
    sudo apt-get install gitlab-runner
    touch {{HOME}}/runner_is_installed.flag
  when: not flag.stat.exists


- name: "Register integration runner"
  shell: |
    sudo apt install -y jq
    register_token=$(curl -X GET --header "PRIVATE-TOKEN: this_is_my_private_token" "http://localhost/gitlab/api/v4/projects/2" 2>/dev/null | jq -r '.runners_token')
    sudo gitlab-runner register --non-interactive --config /etc/gitlab-runner/config.toml --tag-list integration --registration-token $register_token \
      --run-untagged --name "[integration-server] docker" --url http://localhost/gitlab --executor docker --docker-image alpine:latest

#  when: not flag.stat.exists

#    authentication_token=$(curl -X POST --header "PRIVATE-TOKEN: this_is_my_private_token" --data "token=$register_token&description=[integration-server] docker&active=true&run_untagged=true&tag_list=integration" "http://localhost/gitlab/api/v4/runners" 2>/dev/null | jq -r '.token')
#    echo "[[runners]]\n   token = \"$authentication_token\"" >> /etc/gitlab-runner/config.toml


