# vim: ts=2
---
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
    
  
  vars:
    HOME: /home/vagrant
    JAVA_DIRECTORY: "/home/vagrant/java"
    VAGRANT_LIBS: "/home/vagrant/libs"
    JAVA_ARCHIVE: "jdk-11.0.12_linux-x64_bin.tar.gz"
    PROJECT_HOME: "/home/vagrant/webCalculator"
    BASE_PROJECT: "/home/vagrant/base_project"
    CI_SERVER_URL: "http://192.168.33.9:8080/gitlab"

  tasks:
  - include_role:
      name: packages
  - include_role:
      name: java
  - include_role:
      name: git
  
